services:
  # PHP-FPM Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    environment:
      - DB_HOST=mysql # Meaning that's running on localhost
      - DB_PORT=3306
      - DB_DATABASE=smartchat
      - DB_USERNAME=user
      - DB_PASSWORD=pass

  # Nginx Service
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - mysql
    networks:
      - app-network

  # MySQL Service
  mysql:
    image: mysql:8.0
    platform: linux/amd64
    restart: always
    ports:
      - "33060:3306"  # Changed from 3306:3306 to avoid port conflicts
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: smartchat
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    command: --default-authentication-plugin=mysql_native_password

  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    restart: always
    ports:
      - "8081:80"  # Changed from 8081:80 to avoid port conflicts
    environment:
      PMA_HOST: mysql # Meaning that's running on localhost
      PMA_USER: user
      PMA_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: root_password
    depends_on:
      - mysql
    networks:
      - app-network

  # Redis Service
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    command: redis-server --appendonly yes

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  redis_data: